export const FETHCHING_DATA = "FETHCHING_DATA";
export const FETHCING_DATA_SUCCESS = "FETHCING_DATA_SUCCESS";
export const FETHCING_DATA_FAILURE = "FETHCING_DATA_FAILURE";

export const RAGISTER_USER_PENDING = "RAGISTER_USER_PENDING";
export const RAGISTER_USER = "RAGISTER_USER";
export const RAGISTER_USER_ERROR = "RAGISTER_USER_ERROR";

export const LOGIN_USER_PENDING = "LOGIN_USER_PENDING";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";








